server:
  ssl:
    key-store: classpath:server.p12
    key-store-password: password
    key-store-type: PKCS12
    key-password: password
    enabled: true
  port: 9001

spring:
  profiles:
    active: default
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true

logging:
  level:
    org.springframework.cloud: WARN
    org.springframework.context.support.PostProcessorRegistrationDelegate: WARN
    reactor.netty.tcp.TcpServer: OFF